// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.nanotrader.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.nanotrader.domain.AccountprofileDataOnDemand;
import org.springframework.nanotrader.domain.AccountprofileIntegrationTest;
import org.springframework.nanotrader.repository.AccountProfileRepository;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AccountprofileIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AccountprofileIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AccountprofileIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AccountprofileIntegrationTest: @Transactional;
    
    @Autowired
    private AccountprofileDataOnDemand AccountprofileIntegrationTest.dod;
    
    @Autowired
    AccountProfileRepository AccountprofileIntegrationTest.accountProfileRepository;
    
    @Test
    public void AccountprofileIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Accountprofile' failed to initialize correctly", dod.getRandomAccountprofile());
        long count = accountProfileRepository.count();
        Assert.assertTrue("Counter for 'Accountprofile' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AccountprofileIntegrationTest.testFind() {
        Accountprofile obj = dod.getRandomAccountprofile();
        Assert.assertNotNull("Data on demand for 'Accountprofile' failed to initialize correctly", obj);
        Integer id = obj.getProfileid();
        Assert.assertNotNull("Data on demand for 'Accountprofile' failed to provide an identifier", id);
        obj = accountProfileRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Accountprofile' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Accountprofile' returned the incorrect identifier", id, obj.getProfileid());
    }
    
    @Test
    public void AccountprofileIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Accountprofile' failed to initialize correctly", dod.getRandomAccountprofile());
        long count = accountProfileRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Accountprofile', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Accountprofile> result = accountProfileRepository.findAll();
        Assert.assertNotNull("Find all method for 'Accountprofile' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Accountprofile' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AccountprofileIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Accountprofile' failed to initialize correctly", dod.getRandomAccountprofile());
        long count = accountProfileRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Accountprofile> result = accountProfileRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Accountprofile' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Accountprofile' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AccountprofileIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Accountprofile' failed to initialize correctly", dod.getRandomAccountprofile());
        Accountprofile obj = dod.getNewTransientAccountprofile(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Accountprofile' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Accountprofile' identifier to be null", obj.getProfileid());
        accountProfileRepository.save(obj);
        accountProfileRepository.flush();
        Assert.assertNotNull("Expected 'Accountprofile' identifier to no longer be null", obj.getProfileid());
    }
    
    @Test
    public void AccountprofileIntegrationTest.testDelete() {
        Accountprofile obj = dod.getRandomAccountprofile();
        Assert.assertNotNull("Data on demand for 'Accountprofile' failed to initialize correctly", obj);
        Integer id = obj.getProfileid();
        Assert.assertNotNull("Data on demand for 'Accountprofile' failed to provide an identifier", id);
        obj = accountProfileRepository.findOne(id);
        accountProfileRepository.delete(obj);
        accountProfileRepository.flush();
        Assert.assertNull("Failed to remove 'Accountprofile' with identifier '" + id + "'", accountProfileRepository.findOne(id));
    }
    
}
