/**
 * Default internationalization object
 * @author Carlos Soto <carlos.soto>
 * @author Kashyap Parikh
 */
nano.strings = {
    buyShares: 'Buy Shares',
    sellShares: 'Sell Shares',
	location : '3401 Hillview Ave Palo Alto, CA 94304 USA',
    noDataAvailable : 'No Data Available.',
    warning : 'Warning!',
    totalOfHoldings : 'Total Of Holdings',
    sell : 'Sell',
    listOfHoldings : 'List of Holdings',
    purchaseDate : 'Purchase Date',
    symbo : 'Symbol',
    quantity : 'Quantity',
    purchasePrice : 'Purchase Price',
    currentPrice : 'Current Price',
    purchaseBasis : 'Purchase Basis',
    total : 'Total',
    portfolioSummary : 'Portfolio Summary',
    numberOfHoldings : 'Number of Holdings',
    marketValue : 'Market Value',
    totalGainLoss : 'Total Gain/Loss',
    dailyTopGains : 'Daily Top Gains',
    nanotrader : 'NanoTrader',
    dashboard : 'Dashboard',
    portfolio : 'Portfolio',
    trade : 'Trade',
    profile : 'Profile',
    assetDistribution : 'Asset Distribution',
    help : 'Help',
    logout : 'Logout',
    copyright : 'Copyright &copy; 2012 VMWare, Inc. All rights reserved.',
    contactUs : 'Contact us',
    daysGains : "day's gains",
    daysLosses : "day's losses",
    index : 'Index',
    volume : 'Volume',
    change : 'Change',
    login : 'Login',
    enterUsername : 'Please enter your username and password to login.',
    email : 'Email',
    rememberMe : 'Remember me',
    password : 'Password',
    forgotPassword : 'Forgot password?',
    registration : 'Registration',
    dontHaveNanotrader : 'Don\'t have a nanoTrader account yet?',
    createOneNow : 'Create one now!',
    pleaseRegister : 'Please Register me now',
    price : 'Price',
    username : 'Username',
    invalidUser : 'Invaild Username and/or Password. Please try again.',
    ohSnap : 'Oh snap! You got an error!',
    unknowError : 'An unknown error has occurred. Please try again later.',
    accountSummary : 'Account Summary',
    currentBalance : 'Current Balance',
    openingBalance : 'Opening Balance',
    cashBalance : 'Cash Balance',
    portfolioValue : 'Portfolio Value',
    holdingsTotal : 'Total of Holdings',
    currentGainLoss : 'Current Gain/Loss',
    userStatistics : 'User Statistics',
    accountId : 'Account ID',
    accountCreationDate : 'Account Creation Date',
    totalLogins : 'Total Logins',
    sessionCreationDate : 'Session Creation Date',
    sessionExpired : 'Your session has expired. Please login in to continue.',
    registerUserName : 'Register New User',
    enterAccountDetails : 'Please enter test data for creating the account',
    fullName : 'Full name',
    passwordConfirmation : 'Password Confirmation',
    passwordMatching : 'Please make sure Password fields are matching',
    userId : 'User ID',
    creditCardNumber : 'Credit Card Number',
    address : 'Address',
    register : 'Register',
    alreadyRegistered : 'If you have already registered, please enter your login and password on our login page.',
    visitLoginPage : 'Visit login page',
    nanoTraderLogin : 'nanoTrader Login',
    emptyFieldError : 'Please complete all the registration fields.',
    newPassword : 'New Password',
    accountProfile : 'Account Profile',
    update : 'Update',
    name : 'Name',
    phone : 'Phone',
    message : 'Message',
    send : 'Send',
    enterSymbol : 'Enter Symbol',
    getQuote : 'Get Quote',
    symbolDoesNotExist : 'The symbol you specified does not exist. Please try again.',
    recentOrders : 'Recent orders',
    orderId : 'Order ID',
    orderStatus : 'Order Status',
    creationDate : 'Creation Date',
    completionDate : 'Completion Date',
    transactionFee : 'Transaction Fee',
    transactionType : 'Transaction Type',
    symbol  : 'Symbol',
    completed : 'Completed',
    closed : 'Closed',
    cancelled : 'Cancelled',
    orderConfirmation: 'Order Confirmation',
    ok : 'OK',
    cancel : 'Cancel',
    buy : 'Buy',
    uncompleted : 'Uncompleted',
    pending : 'Pending',
    quote : 'Quote',
    recentTransactions : 'Recent Transactions',
    applicationOverview : 'Application Overview',    
    errorOcurred : 'An error has occurred.',
    anError : 'You received an error.',
    fullnameError : 'Please re-enter your Full name.',
    emailError : 'Please re-enter your e-mail address.',
    passwdError : 'Error! You entered invalid characters into the password field. Please re-enter your password.', 
    useridError : 'Please re-enter your username.', //userid???
    usernameError : 'Please re-enter your username.',
    openbalanceError : 'Please re-enter your opening balance.',
    creditcardError : 'Please re-enter your credit card number',
    addressError : 'Please re-enter your address',
    gainingMsg : 'This chart shows the top 4 gaining stocks in your portfolio',
    portfolioMsg : 'This chart shows the cash balance and the portfolio value as a % of the total assets in your account',
    loginPage : 'Login Page',
    enterNumUsers : 'Number of accounts to create',
    userdataHeadsUp : 'Warning! This will delete existing user accounts, associated data and recreate them (excluding admin user)',
    perfHeadsUp : 'Heads up! This functionality is currently available only on remote Linux VMs with SSH enabled/groovy installed',
    enterNumPerfUsers : 'Number of accounts to create (minimum 100)',
    enterNumPerfOrders : 'Number of stock orders to create (minimum 100)',
    selectPerfType : 'Select the type of Performance test',
    fixedOrderLoadMsg : 'Single user with fixed stock(VMW) orders',
    multiOrdersLoadMsg : 'Multiple users with random stock orders',
    enterNumBuyOrders : 'Number of buy orders for each user',
    enterNumVMs : 'Number of client VMs to connect',
    showWipeDBWarning : 'Warning: This action is not recoverable. It will wipe your database.',
    showIntegerError : 'Please enter a valid number',
    admin : 'Admin',
    createUsers : 'Create Users',
    dataPop : "Populating data ...",
    userCreationProgressMsg : "Creating users ...",
    userCreationMessage : "Users Created ...",
    dataPopComplete : "Data population complete ...",
    loggingOut : "Logging out... Please log back in with new user id",
    error : 'Error!',
    goToLoginPage : 'Go To Login Page',
    quantityError :  'Error! Quantity must be a positive number.',
    buyOrderMessage : 'Your order is submitted for processing...',
    killTCServer : 'Kill TCServer',
    crashTCServer : 'Crash TCServer',
    killRabbitMQ : 'Kill RabbitMQ',
    stopRabbitMQ : 'Stop RabbitMQ',
    killSQLFire : 'Kill SQLFire',
    stopSQLFire : 'Stop SQLFire',
    waitKillTCServerStatus : 'Waiting for TC Server to be killed...',
    killTCServerStatus : 'TC Server killed successfully',
    waitCrashTCServerStatus : 'Waiting for TC Server to crash...',
    crashTCServerStatus : 'TC Server crashed successfully',
    waitSQLFireStatus  : 'Waiting for SQLFire server to be killed...',
    killSqlFireServerStatus : 'SQLFire Server killed successfully',
    resourceId : 'Resource Id',
    serverName : 'Server Name',
    serverType : 'Server Type',
    control : 'Control Actions'
};
