Ext.define('SpringTrader.view.MarketSummary', {
    extend: 'Ext.dataview.DataView',
    xtype: 'marketsummary',
    config: {
        scrollable: false,
        styleHtmlContent: true,
        height: 216,
        cls: 'well show-well market-summary',
        itemTpl: [
            '<div class="centered width-half">',
            '<table class="table table-condensed">',
            '    <tr><td class="right">Index</td><td class="right" id="ms-index">{[ values.tradeStockIndexAverage.toFixed(2) ]}</td></tr>',
            '    <tr><td class="right">Volume</td><td class="right" id="ms-volume">{[ values.tradeStockIndexVolume.toFixed(0) ]}</td></tr>',
            '    <tr><td class="right">Change</td><td id="ms-change" class="right {[ values.change >= 0 ? "green-color" : "red-color" ]}">{[ values.change.toFixed(2) ]} {[ values.change >= 0 ? "↑" : "↓" ]}</td></tr>',
            '</table>',
            '</div>',
            '<div class="pull-left width-half">',
            '<table class="table table-condensed gainers">',
            "<tr><th class='green-color centered' colspan=2><i class='icon-custom icon-gains'></i>day's gains</th></tr>",
            '<tpl for="topGainers">',
            '    <tr>',
            '        <td class="symbols centered">{symbol}</td>',
            '        <td class="changes right green-color">{change1} ↑</td>',
            '    </tr>',
            '</tpl>',
            '</table>',
            '</div>',
            '<div class="pull-right width-half">',
            '<table class="table table-condensed losers">',
            "<tr><th class='red-color centered' colspan=2><i class='icon-custom icon-lost'></i>day's losses</th></tr>",
            '<tpl for="topLosers">',
            '    <tr>',
            '        <td class="symbols centered">{symbol}</td>',
            '        <td class="changes right red-color">{change1} ↓</td>',
            '    </tr>',
            '</tpl>',
            '</table>',
            '</div>'
        ],
        emptyText: 'No market data',
        loadingText: false,
        store: 'marketsummary'
    }
});
