Ext.define('SpringTrader.view.MarketSummary', {
	extend: 'Ext.dataview.DataView',
	xtype: 'marketsummary',
	config: {
        scrollable: false,
        height: 328,
        itemTpl: [
'<div class="market-summary">',
            '<h2 class="centered">Indices</h2>',
'            <table class="table table-condensed">',
'        <tr><td class="right">Index:</td><td id="ms-index">{[ values.tradeStockIndexAverage.toFixed(2) ]}</td></tr>',
'        <tr><td class="right">Volume:</td><td id="ms-volume">{[ values.tradeStockIndexVolume.toFixed(2) ]}</td></tr>',
'    <tr><td class="right">Change:</td><td id="ms-change">{[ values.change.toFixed(2) ]}</td></tr>',
'</table>',
            '<h2 class="centered">Losers</h2>',
'<table class="table table-condensed losers">',
'    <tr>',
'        <tpl for="topLosers">',
'            <td class="symbols centered">{symbol}</td>',
'        </tpl>',
'    </tr>',
            '    <tr>',
            '        <tpl for="topLosers">',
            '            <td class="prices centered">{price}</td>',
            '        </tpl>',
            '    </tr>',
            '    <tr>',
            '        <tpl for="topLosers">',
            '            <td class="changes centered">{change1}</td>',
            '        </tpl>',
            '    </tr>',
'</table>',
            '<h2 class="centered">Gainers</h2>',
            '<table class="table table-condensed gainers">',
            '    <tr>',
            '        <tpl for="topGainers">',
                '            <td class="symbols centered">{symbol}</td>',
                '        </tpl>',
            '    </tr>',
            '    <tr>',
            '        <tpl for="topGainers">',
                '            <td class="prices centered">{price}</td>',
                '        </tpl>',
            '    </tr>',
            '    <tr>',
            '        <tpl for="topGainers">',
                '            <td class="changes centered">{change1}</td>',
                '        </tpl>',
            '    </tr>',
            '</table>',
'</div>'
],
        emptyText: 'No market data',
        loadingText: 'Loading...',
        store: 'marketsummary'
    }
});
