/**
 * Default internationalization object
 * @author Carlos Soto <carlos.soto@lognllc.com>
 */
nano.strings = {
    sell : 'Sell',
    listOfHoldings : 'List of Holdings',
    purchaseDate : 'Purchase Date',
    symbo : 'Symbol',
    quantity : 'Quantity',
    purchasePrice : 'Purchase Price',
    currentPrice : 'Current Price',
    purchaseBasis : 'Purchase Basis',
    total : 'Total',
    portfolioSummary : 'Portfolio Summary',
    numberOfHoldings : 'Number of Holdings',
    purchaseBasis : 'Purchase Basis',
    marketValue : 'Market Value',
    totalGainLoss : 'Total Gain/Loss',
    dailyTopGains : 'Daily Top Gains',
    nanotrader : 'NanoTrader',
    dashboard : 'Dashboard',
    portfolio : 'Portfolio',
    trade : 'Trade',
    profile : 'Profile',
    assetDistribution : 'Asset Distribution',
    help : 'Help',
    logout : 'Logout',
    copyright : 'Copyright &copy; 2012 VMWare, Inc. All rights reserved.',
    contactUs : 'Contact us',
    daysGains : 'days gains',
    daysLosses : 'days losses',
    index : 'Index',
    volume : 'Volume',
    change : 'Change',
    login : 'Login',
    enterUsername : 'Please enter your username and password to login.',
    email : 'Email',
    rememberMe : 'Remember me',
    password : 'Password',
    forgotPassword : 'Forgot password?',
    registration : 'Registration',
    dontHaveNanotrader : 'Don\'t have a nanoTrader account yet?',
    createOneNow : 'Create one now!',
    pleaseRegister : 'Please Register me now',
    price : 'Price',
    username : 'Username',
    invalidUser : 'Invaild Username and/or Password. Please try again.',
    ohSnap : 'Oh snap! You got an error!',
    unknowError : 'An unknown error has occurred. Please try again alter.',
    accountSummary : 'Account Summary',
    currentBalance : 'Current Balance',
    openingBalance : 'Opening Balance',
    cashBalance : 'Cash Balance',
    portfolioValue : 'Portfolio Value',
    holdingsTotal : 'Total of Holdings',
    currentGainLoss : 'Current Gain/Loss',
    userStatistics : 'User Statistics',
    accountId : 'Account Id',
    accountCreationDate : 'Account Creation Date',
    totalLogins : 'Total Logins',
    sessionCreatedDate : 'Session Created Date',
    sessionExpired : 'Your session has expired. Please login in to continue.',
    contactUs : 'Contact Us',
    registerUserName : 'Register New User',
    enterAccountDetails : 'Please enter your account details',
    fullName : 'Full name',
    passwordConfirmation : 'Password Confirmation',
    passwordMatching : 'Please make sure Password fields are matching',
    userId : 'User ID',
    creditCardNumber : 'Credit Card Number',
    address : 'Address',
    register : 'Register',
    alreadyRegistered : 'If you already registered enter your login and password on login page',
    visitLoginPage : 'Visit login page',
    nanoTraderLogin : 'NanoTrader Login',
    emptyFieldError : 'Please complete all the registration fields.',
    newPassword : 'New Password',
    accountProfile : 'Account Profile',
    update : 'Update',
    name : 'Name',
    phone : 'Phone',
    message : 'Message',
    send : 'Send',
    enterSymbol : 'Enter Symbol',
    getQuote : 'Get Quote',
    symbolDoesNotExist : 'Ticker symbol does not exist',
    recentOrders : 'Recent orders',
    orderId : 'Order ID',
    orderStatus : 'Order Status',
    creationDate : 'Creation Date',
    completionDate : 'Completion Date',
    transactionFee : 'Transaction Fee',
    transactionType : 'Transaction Type',
    symbol  : 'Symbol',
    quantity : 'Quantity',
    completed : 'Completed',
    orderConfirmation: 'Order Confirmation',
    ok : 'OK',
    cancel : 'Cancel',
    buy : 'Buy',
    uncompleted : 'Uncompleted',
    pending : 'Pending',
    price : 'Price',
    quote : 'Quote',
    recentTransactions : 'Recent Transactions',
    applicationOverview : 'Application Overview',    
    errorOcurred : 'An error has occurred.',
    fullnameError : 'Error! You got an Fullname field validation error!',
    emailError : 'Error! You got an Email field validation error!',
    passwdError : 'Error! You got an Password field validation error!',
    useridError : 'Error! You got an Username field validation error!',
    openbalanceError : 'Error! You got an Open balance field validation error!',
    creditcardError : 'Error! You got an Creditcard field validation error!',
    addressError : 'Error! You got an Address field validation error!',
    gainingMsg : 'This chart shows the top 4 gaining stocks in your portfolio',
    portfolioMsg : 'This chart shows the cash balance and the portfolio value as a % of the total assets in your account'
};
