/**
 * Default internationalization object
 * @author Carlos Soto <carlos.soto@lognllc.com>
 */
nano.strings = {
    dailyTopGains : 'Daily Top Gains',
    nanotrader : 'NanoTrader',
    dashboard : 'dashboard',
    portfolio : 'portfolio',
    trade : 'trade',
    profile : 'Profile',
    assetDistribution : 'Asset Distribution',
    help : 'Help',
    logout : 'Logout',
    copyright : 'Copyright &copy; 2012 VMWare, Inc. All rights reserved.',
    contactUs : 'Contact us',
    daysGains : 'days gains',
    daysLosses : 'days losses',
    index : 'Index',
    volume : 'Volume',
    change : 'Change',
    login : 'Login',
    enterUsername : 'Please enter your username and password to login.',
    email : 'Email',
    rememberMe : 'Remember me',
    password : 'Password',
    forgotPassword : 'Forgot password?',
    registration : 'Registration',
    dontHaveNanotrader : 'Don\'t have a NanoTrade login and password yet?',
    pleaseRegister : 'Please Register me now',
    price : 'Price',
    username : 'Username',
    invalidUser : 'Invaild Username and/or Password. Please try again.',
    ohSnap : 'Oh snap! You got an error!',
    unknowError : 'An unknown error has occurred. Please try again alter.',
    accountSummary : 'Account Summary',
    currentBalance : 'Current Balance',
    openingBalance : 'Opening Balance',
    cashBalance : 'Cash Balance',
    portfolioValue : 'Portfolio Value',
    holdingsTotal : 'Total of Holdings',
    currentGainLoss : 'Current Gain/Loss',
    userStatistics : 'User Statistics',
    accountId : 'Account Id',
    accountCreationDate : 'Account Creation Date',
    totalLogins : 'Total Logins',
    sessionCreatedDate : 'Session Created Date',
    sessionExpired : 'Your session has expired. Please login in to continue.',
    contactUs : 'Contact Us'
};